@isTest
private class customlookupcontrollertest {
    static testmethod void getLookUp1()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Account', 'unitOrganisation', 'Cornea');
    }
    static testmethod void getLookUp2()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Account', 'unitOrganisation1', 'Cornea');
    }
    static testmethod void getLookUp3()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'hrcpcounselor', 'Cornea');
    }
    static testmethod void getLookUp4()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'unitOrganisation', 'Cornea');
    }
    static testmethod void getLookUp5()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'hcrpHospital', 'Cornea');
    }
    static testmethod void getLookUp6()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'recoverytech', 'Cornea');
    }
    static testmethod void getLookUp7()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'specularTech', 'Cornea');
    }
    static testmethod void getLookUp8()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'ekTech', 'Cornea');
    }
    static testmethod void getLookUp9()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'ekCirculator', 'Cornea');
    }
    static testmethod void getLookUp10()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'slitLampTech', 'Cornea');
    }
    static testmethod void getLookUp11()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'serologytech', 'Cornea');
    }
    static testmethod void getLookUp12()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'microbiologist', 'Cornea');
    }
    static testmethod void getLookUp13()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'EyebankAndQA', 'Cornea');
    }
    static testmethod void getLookUp14()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'EyebankAndQA1', 'Cornea');
    }
    static testmethod void getLookUp15()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'EyebankAndQA1', 'Cornea');
    }
    static testmethod void getLookUp16()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'handBy', 'Cornea');
    }
    static testmethod void getLookUp17()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'to', 'Cornea');
    }
    static testmethod void getLookUp18()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'reqorg', 'Cornea');
    }
    static testmethod void getLookUp19()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'transsurgeon', 'Cornea');
    }
    static testmethod void getLookUp20()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'transHosp', 'Cornea');
    }
    static testmethod void getLookUp21()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'eyebankPrecut', 'Cornea');
    }
    static testmethod void getLookUp22()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'completedBy', 'Cornea');
    }
    static testmethod void getLookUp23()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'specularTech1', 'Cornea');
    }
    static testmethod void getLookUp24()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'specularTechTiss', 'Cornea');
    }
    static testmethod void getLookUp25()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Contact', 'slitLampTech1', 'Cornea');
    }
    static testmethod void getLookUp26()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'EMR__c', 'slitLampTech1', 'Cornea');
    }
    static testmethod void getLookUp27()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Tissue_Evaluation__c', 'slitLampTech1', 'Cornea');
    }
    static testmethod void getLookUp28()
    {
        customLookUpController.fetchLookUpValues('searchKeyWord', 'Placement__c', 'slitLampTech1', 'Cornea');
    }


}